In [4]:
import numpy as np

## 다차원 배열(Arrays)
### ndarray(n-dimensional array): 같은 종류의 데이터를 담을 수 있는 다차월 배열, 모든 원소는 같은 자료형이어야 함!! 
#### 배열의 구성 1. shape - 각 차원의 크기를 알려주는 튜플
#### 　　　　　2. type - 배열에 저장된 자료형을 알려주는 객체 

In [5]:
# 일반적인 리스트를 먼저 확인!
a = [1, 2, 3, 4, 5, 6]
print(a)
b = [[1, 2, 3], [4, 5, 6]] # 2차원 행렬을 리스트로 표현 
print(b)
c = [1, 'a', 3.5] # 서로다른 type의 데이터 저장이 가능한 '리스트'
print(c)

[1, 2, 3, 4, 5, 6]
[[1, 2, 3], [4, 5, 6]]
[1, 'a', 3.5]


#### ndarray는 []를 이용하여 인덱싱!

In [7]:
a = np.array([1, 2, 3])  # np.array로 1차원 배열 생성
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 #생성된 배열의 한 원소를 변경
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [8]:
b = np.array([[1,2,3],[4,5,6]])   # np.array로 2차원 배열 생성
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
print(b.shape) # 생성된 배열의 크기를 확인!
print(b[0, 0], b[0, 1], b[1, 0]) #생성된 배열에서 indexing

(2, 3)
1 2 4


In [11]:
# np.zeros - 모든 원소값이 0인 배열을 생성 
a = np.zeros((2, 3))  
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# np.ones - 모든 원소값이 1인 배열을 생성 
b = np.ones((3, 4)) 
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# np.full - 모든 원소를 원하는 값으로 하는 배열 생성
c = np.full((2, 4), 7) 
print(c)

[[7 7 7 7]
 [7 7 7 7]]


In [14]:
# np.eye - 2X2의 단위행렬 (identity matrix)을 생성
d = np.eye(4)    
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# np.random.random - 무작위값으로 원소를 이루는 배열 생성
e = np.random.random((2,4)) 
print(e)

[[0.22378748 0.19627891 0.60110896 0.26595959]
 [0.31726987 0.04772095 0.58458133 0.46528797]]


## 배열 인덱싱 (Array indexing)

#### Slicing - 리스트와 유사한 슬라이싱 / 다차원 배열인 ndarray은 각 차원에 대한 슬라이싱이 가능
#### %주의% 슬라이스로 잘라서 만든 배열은 원래의 배열과 값을 공유 - 수정할 경우 원래 배열의 값이 변경됨! 

In [22]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]] 
# -> 모양의 배열을 생성

# 생성된 배열 a에서 
# [[2 3]
#  [6 7]]
# 만 추출하기!

b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [23]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(b)
print(a) # b가 변경되어 a의 값도 변경됨 

2
[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
# 열.copy 를 이용하면 값을 복사해서 새로운 배열을 생성할 수 있음!
c = b.copy()
c[0, 0] = 55
print(c)
print(b)

[[55  3]
 [ 6  7]]
[[77  3]
 [ 6  7]]


In [26]:
# 새로운 (3,4) shape의 배열 생성
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [27]:
#차원 감소
row_r1 = a[1, :] 
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [28]:
# 차원 유지
row_r2 = a[1:2, :]  
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [29]:
row_r3 = a[2, :] 
print(row_r3, row_r3.shape)

[ 9 10 11 12] (4,)


In [ ]:
# 컬럼을 잘라낼 때에도 똑같이 적용됨!
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

In [32]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a, a.shape)

# 정수 배열 indexing
print(a[[0, 1, 2], [0, 1, 0]]) # -> shape는 (3, )

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 4 5]
[1 4 5]


In [34]:
# 같은 요소도 가져올 수 있음
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [35]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
# np.arange - ndarray 형태로 모든 값을 생성!
print(np.arange(4))
print(range(4))

[0 1 2 3]
range(0, 4)


In [38]:
# 정수 배열
b = np.array([0, 2, 0, 1])

# a의 배열에서 b의 각 행 위의 열 값을 가져오기
print(a[np.arange(4), b])

[ 1  6  7 11]


In [39]:
# 가져온 열 값에 각 10을 더하기
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#### 불리안 배열 indexing - 배열에서 원하는 요소들만 추출! (특정 조건을 만족하는 요소들만 골라내고자 할 때 자주 사용)

In [41]:
bb = np.array([1, 2, 3, 4, 5, 6])

# bb 배열에서 해당 비교연산자 적용 결과
bb > 3

array([False, False, False,  True,  True,  True])

In [42]:
# 벡터에 대한 불리안 인덱싱

bb[bb > 3] # bb 값 중에서 3보다 큰 값만 반환 

array([4, 5, 6])

In [43]:
a = np.array([[1,2], [3, 4], [5, 6]])

# a 배열의 각 요소들이 2보다 큰지 아닌지 반환 (True or False로 반환)
bool_idx = (a > 2)  
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [44]:
# 불리안 배열의 값이 true인 요소들만 반환
print(a[bool_idx])
# 같은 방식
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


### 데이터 타입의 명시적 선언 
#### ndarray는 모두 같은 타입의 요소로 이루어짐, 지정하지 않는 경우 자동으로 선택

In [50]:
#자동으로 타입 선택
x = np.array([1, 2])
y = np.array([1.0, 2.0])

#타입을 명시적으로 지정
z = np.array([1, 2], dtype=np.int64)

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


array([1, 2], dtype=int64)

In [51]:
#값은 정수 - 타입을 잘못 선택
#설정한 타입으로 생성
z = np.array([1, 2], dtype=np.float32)
z

array([1., 2.], dtype=float32)

### 배열의 연산
#### 기본적으로 '요소단위'로 이뤄지고, 연산자 및 함수 사용 가능!

In [54]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [55]:
# 요소들의 합 - 결과로 ndarray 생성 
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [56]:
# 요소의 차
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [57]:
# 요소의 곱 
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# 요소의 나눗셈
print(x / y)
print(np.divide(x, y))

In [ ]:
# 요소의 제곱근
print(np.sqrt(x))

In [61]:
import math
a = [1, 2, 3, 4]

#sqrt - 리스트에서는 적용 XXX
math.sqrt(a) 

TypeError: must be real number, not list

### dot 합수를 사용한 벡터의 내적(inner product) 

In [62]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x, x.shape)
print(y, y.shape)
print(v, v.shape)
print(w, w.shape)

[[1 2]
 [3 4]] (2, 2)
[[5 6]
 [7 8]] (2, 2)
[ 9 10] (2,)
[11 12] (2,)


In [64]:
# 벡터 내적(Inner product)
print(v.dot(w))
print(np.dot(v, w))

# 행렬과 벡터 간 곱셈
print(x.dot(v))
print(np.dot(x, v))

# 행렬 곱셈
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [65]:
x = np.array([[1,2],[3,4]])
print(x)

print(np.sum(x))  # 모든 요소들의 합
print(np.sum(x, axis=0))  # 열들의 합 
print(np.sum(x, axis=1))  # 행들의 합

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [68]:
#전치행렬 (transposed matrix)
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.T)

v = np.array([[1,2,3]])
print(v)
print(v.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]]
[[1]
 [2]
 [3]]


### 브로드캐스팅(Broadcasting) - 크기가 다른 배열에 대한 연산 

In [70]:
# 벡터 v 를 행렬 x의 모든 행에 더하고 싶음!
# v를 모든 x의 행에 더한 값을 y에 저장
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print('x =\n', x)
v = np.array([1, 0, 1])
y = np.empty_like(x)   # x와 shape가 동일한 빈 행렬 y를 생성 

# for반복문을 이용해서 x의 각 행에 v를 더함 - y에 저장 
for i in range(4):
    y[i, :] = x[i, :] + v

#결과값 y를 출력
print('y =\n', y)


x =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
y =
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [71]:
# 원하는 값을 출력할 수 있지만, 만약 x의 크기가 커질경우 속도가 느림
# v를 반복해서 x와 같은 shape으로 만든다음에 x에 더하는 방식

vv = np.tile(v, (4, 1))  # x 행의 수만큼 v를 반복
print(vv)                # x와 크기가 같은 v를 vv에 저장

y = x + vv # 같은 크기의 x와 vv를 더함 
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [72]:
# 브로드캐스팅을 이용해서 편하게 구현가능!
#브로드캐스팅 ex1
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  
#shpae가 다른 x와 v - 자동으로 브로드캐스팅!
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [73]:
#브로드캐스팅 ex2
v = np.array([1,2,3]) # shape는 (3,)
w = np.array([4,5])   # shape는 (2,)
# 위의 경우, v와 w의 shape이 다르므로 요소곱을 하는 경우 에러가 발생함
# 먼저 v를 열로 바꿔서 shape을 (3, 1)로 만듬
# 그 다음 브로드캐스팅을 적용 - v와 w가 (3, 2)로 확장
# 마지막으로 요소곱을 실행
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [77]:
# 벡터를 행렬의 각 행에 더하고자 하는 경우
x = np.array([[1,2,3], [4,5,6]])
print('x =\n', x)
# shape이 (2,3)인 x와 (3,)인 v를 브로드캐스트!

print('result =\n', x + v)

x =
 [[1 2 3]
 [4 5 6]]
result =
 [[2 4 6]
 [5 7 9]]


In [78]:
# x의 각 행 + w 
# x와 w는 크기가 다름!
# w를 (2,1)로 reshape -> 이후 브로드캐스트
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [76]:
# x 행렬 * 상수
# Numpy는 스칼라를 shape ()로 취급;
# 따라서 x에 맞춰 스칼라를 shape (2, 3)으로 브로드캐스팅이 가능
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]
